# Generated by Django 3.0.8 on 2020-07-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_book_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='csv',
            field=models.FileField(default='demo', upload_to='metadata/csvs/'),
            preserve_default=False,
        ),
    ]
